# Form implementation generated from reading ui file 'addEditCoffeeform.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.verticalLayout.addWidget(self.roastLineEdit)
        self.typeLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.verticalLayout.addWidget(self.typeLineEdit)
        self.tasteLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tasteLineEdit.setObjectName("tasteLineEdit")
        self.verticalLayout.addWidget(self.tasteLineEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.volumeLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.verticalLayout.addWidget(self.volumeLineEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название"))
        self.roastLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Обжарка"))
        self.typeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Тип"))
        self.tasteLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Вкус"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена"))
        self.volumeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Объем"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
